# Generated by Django 5.2.5 on 2025-08-18 12:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_collected', models.DateTimeField(auto_now_add=True, verbose_name='Time Collected')),
                ('jobs_run', models.IntegerField(default=0)),
                ('jobs_success', models.IntegerField(default=0)),
                ('jobs_failure', models.IntegerField(default=0)),
                ('users_count', models.IntegerField(default=0)),
                ('users_active', models.IntegerField(default=0)),
                ('job_files_total', models.IntegerField(default=0)),
                ('job_files_size', models.BigIntegerField(default=0)),
                ('job_files_added', models.IntegerField(default=0)),
                ('job_files_added_size', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FileMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_collected', models.DateTimeField(auto_now_add=True, verbose_name='Time Collected')),
                ('size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(choices=[('job', 'Job')], default='job', max_length=6)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('name', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('error_info', models.TextField(blank=True, default='')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Time Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('task_ids', models.JSONField(blank=True, default=list)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('RETRY', 'Retry'), ('REVOKED', 'Revoked')], default='PENDING', max_length=10)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
                'ordering': ['-created'],
                'permissions': [('run_job', 'Can run cutout jobs')],
            },
        ),
        migrations.CreateModel(
            name='JobFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='')),
                ('size', models.BigIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cutout.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_collected', models.DateTimeField(auto_now_add=True, verbose_name='Time Collected')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('RETRY', 'Retry'), ('REVOKED', 'Revoked')], max_length=10)),
                ('config', models.JSONField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
