# Generated by Django 5.2.5 on 2025-08-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cutout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created'], 'permissions': [('run_job', 'Can run cutout jobs')], 'verbose_name': 'job', 'verbose_name_plural': 'jobs'},
        ),
    ]
